# Start from the base image provided by OpenSearch
FROM opensearchproject/logstash-oss-with-opensearch-output-plugin:8.9.0

# Install the required 'logstash-output-opensearch' plugin
RUN logstash-plugin install logstash-input-jms